#!/bin/bash

# Prints a file at the Inria-SIF printer, by sending the appropriate
# email to mobile-saclay@zimbra-local.inria.fr

# Set IUSER to your Inria user name XX.YY
IUSER=XX.YY

FILE=$1

if [ X$FILE = X ] ; then
	echo "Error: needs filename as argument"
	exit 1
fi

if ! [ -r $FILE ] ; then
	echo "Error: Cannot read file $FILE"
	exit 1
fi

FTYPE=$(file -bL $FILE | awk '{print $1}')
if ! [ $FTYPE = 'PDF' ] && ! [ $FTYPE = 'PostScript' ] ; then
	echo "Error: I can only handle PS or PDF files"
	exit 1
fi

TMPDIR=$(mktemp -d)

if ! [ -w $TMPDIR ] ; then
	echo "Error: Cannot write to temporary directory $TMPDIR"
	exit 1
fi

# Clean up pdf file
if [ $FTYPE = 'PDF' ] ; then
	pdf2ps $FILE $TMPDIR/p.ps
fi
ps2pdf12 $TMPDIR/p.ps $TMPDIR/p.pdf

# Pack file as attachment
mpack -s "" -o $TMPDIR/m $TMPDIR/p.pdf

# Generate email
echo "From: $IUSERg@inria.fr" > $TMPDIR/mm
cat $TMPDIR/m >> $TMPDIR/mm

# Finally, send email
cat $TMPDIR/mm | ssmtp mobile-saclay@zimbra-local.inria.fr

# Clean up
rm -rf $TMPDIR

